name: CI/CD to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Replace with your package manager and setup

      - name: Build
        run: npm run build  # Replace with your build command

      - name: Deploy to EC2
        run: |
          ssh -i /home/addweb/keys ubuntu@52.66.43.136 "cd /var/www/html/ && git pull && npm install && npm run build"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
