name: Copy Source Code with SSH

on:
  push:
    branches:
      - main

jobs:
  copy-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Copy Source Code
      run: |
        cp -r path/to/source/code destination/folder/
        git add destination/folder
        git commit -m "Copy source code using GitHub Actions"
        git push
