on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ls -al
            mkdir -p myapp  # Create the directory if it doesn't exist
            cd myapp
            sudo chown -R ubuntu:ubuntu myapp/
            sudo chmod -R 777 myapp/
            git init  # Initialize Git repository if not already done
            git remote add origin git@github.com:Akshaymore5233/myapp.git
            git pull origin main
