name: Copy Repository to EC2

on:
  push:
    branches:
      - main

jobs:
  copy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Repository
      run: tar -czf repository.tar.gz *

    - name: Copy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: repository.tar.gz
        target: /mnt

    - name: SSH into EC2 and Extract
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'cd /mnt'
