name: Copy Repository to EC2

on:
  push:
    branches:
      - main

jobs:
  copy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Repository
      run: |
        find . -maxdepth 1 -not -name '.' -exec echo {} \; | tar -czf repository.tar.gz -T -pwd
        pwd 

    - name: Copy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: repository.tar.gz
        target: /mnt
    - name: SSH into EC2 and Extract
      run: |
        pwd
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 
        pwd
        sudo chown -R ubuntu:ubuntu /mnt/
        cd /mnt
        sudo chmod 777 repository.tar.gz
        sudo tar -xzf /tmp/ZgBtrWzyly.tar.gz  