name: Copy Repository to EC2

on:
  push:
    branches:
      - main

jobs:
  copy-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Repository
      run: |
        find . -maxdepth 1 -not -name '.' -exec echo {} \; | tar -czf repository.tar.gz -T -pwd
       
    - name: Copy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: repository.tar.gz
        target: /mnt
 