name: test
on:
 push: 
   branches: [main]
 pull_request:
   branches: [main]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: install ssh keys
       run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
     - name: connect and pull
       run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          echo ----- change Directory -----
          cd ${{ secrets.WORK_DIR }}
          echo ----- git checkout -----
          git checkout ${{ secrets.STAGE_BRANCH }}
          echo ----- git pull -----
          git pull origin ${{ secrets.STAGE_BRANCH }}
          /usr/bin/pm2 restart all
          exit
        EOF    
     - name: cleanup
       run: rm -rf ~/.ssh

