name: WordPress Deployment to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 php mysql-server
          sudo service apache2 start
          sudo service mysql start

#      - name: Set up WordPress
#        run: |
          # Navigate to the web root directory
          cd /var/www/html/github_action_phpcodedeploy
          # Remove the default HTML file
          #sudo rm index.html

          # Clone or update your WordPress repository
          git pull

          # Configure your WordPress site
         # cp wp-config-sample.php wp-config.php
         # sed -i 's/database_name_here/your_database_name/' wp-config.php
         # sed -i 's/username_here/your_database_username/' wp-config.php
         # sed -i 's/password_here/your_database_password/' wp-config.php

          # Install or update WordPress plugins and themes
         # wp plugin install <plugin-name> --activate
         # wp theme update --all

          # You may also need to import your database

      - name: Deploy to EC2
        run: |
          ssh -i /home/addweb/keys ubuntu@172.31.45.14 "cd /var/www/html/ && git pull"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
