name: EC2 Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        ssh-keyscan -H 172.31.45.14 >> ~/.ssh/known_hosts
        ssh -i key.pem ${{ secrets.SSH_USERNAME }}@172.31.45.14 "echo SSH Connection Established"

    - name: Deploy code to EC2
      run: |
        # Add your deployment commands here
        # Example: scp -i key.pem -r path/to/local/code ${{ secrets.SSH_USERNAME }}@your-ec2-instance-ip:/path/to/remote/directory
        # Example: ssh -i key.pem ${{ secrets.SSH_USERNAME }}@your-ec2-instance-ip "cd /path/to/remote/directory && git pull"

    - name: Clean up
      run: |
        rm -f key.pem
