name: WordPress Deployment to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -i /home/addweb/keys ubuntu@172.31.45.14 "cd /var/www/html/github_action_phpcodedeploy && git pull"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
